# -*- coding: utf-8 -*-
"""data_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NhYzNCpHz4hom03oSAuspqkqgePq98-b
"""

import json
import random
from typing import List, Dict, Tuple

# Digit to word mapping
DIGIT_WORDS = {
    '0': 'zero', '1': 'one', '2': 'two', '3': 'three', '4': 'four',
    '5': 'five', '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine'
}

# Common names
FIRST_NAMES = ['aditya', 'neha', 'rahul', 'priya', 'amit', 'pooja', 'ravi', 'shreya',
               'vikram', 'ananya', 'rohan', 'meera', 'sanjay', 'kiran', 'deepak', 'soumya']
LAST_NAMES = ['sharma', 'patel', 'singh', 'kumar', 'gupta', 'verma', 'reddy', 'rao',
              'mehta', 'iyer', 'joshi', 'nair', 'pillai', 'agarwal', 'dubey', 'khan']

# Cities
CITIES = ['mumbai', 'delhi', 'bangalore', 'hyderabad', 'chennai', 'kolkata',
          'pune', 'ahmedabad', 'jaipur', 'surat', 'lucknow', 'nagpur']

# Locations
LOCATIONS = ['mg road', 'koramangala', 'banjara hills', 'salt lake', 'whitefield',
             'electronic city', 'old airport road', 'indiranagar', 'velachery', 'powai']

# Email domains
EMAIL_DOMAINS = ['gmail.com', 'yahoo.com', 'hotmail.com', 'outlook.com',
                 'rediffmail.com', 'protonmail.com']

# Months
MONTHS = ['january', 'february', 'march', 'april', 'may', 'june',
          'july', 'august', 'september', 'october', 'november', 'december']


def digits_to_words(digits: str) -> str:
    """Convert digit string to spoken words with occasional 'double' for repeated digits"""
    words = []
    i = 0
    while i < len(digits):
        if i < len(digits) - 1 and digits[i] == digits[i+1] and random.random() < 0.3:
            words.append(f"double {DIGIT_WORDS[digits[i]]}")
            i += 2
        else:
            words.append(DIGIT_WORDS[digits[i]])
            i += 1
    return ' '.join(words)


def generate_credit_card() -> Tuple[str, str]:
    """Generate spelled-out credit card and formatted version"""
    # Generate 16 digits
    digits = ''.join([str(random.randint(0, 9)) for _ in range(16)])

    # Sometimes use dashes (for variety)
    if random.random() < 0.3:
        formatted = f"{digits[:4]}-{digits[4:8]} {digits[8:12]} {digits[12:]}"
    else:
        spoken = digits_to_words(digits)
        formatted = spoken

    return formatted, 16


def generate_phone() -> Tuple[str, str]:
    """Generate spelled-out phone number"""
    digits = ''.join([str(random.randint(0, 9)) for _ in range(10)])

    # Sometimes use space formatting
    if random.random() < 0.3:
        formatted = f"{digits[:5]} {digits[5:]}"
    else:
        formatted = digits_to_words(digits)

    return formatted, 10


def generate_email(name: str) -> str:
    """Generate email in STT format"""
    domain = random.choice(EMAIL_DOMAINS)
    domain_parts = domain.replace('.', ' dot ')

    # Various email formats
    formats = [
        f"{name} dot {random.choice(LAST_NAMES)} at {domain_parts}",
        f"{name}.{random.choice(LAST_NAMES)}@{domain}",
    ]

    return random.choice(formats)


def generate_date() -> str:
    """Generate date in various formats"""
    day = random.randint(1, 28)
    month = random.choice(MONTHS)
    year = random.randint(2023, 2026)

    formats = [
        f"{day} {month} {year}",
        f"{day:02d}/{random.randint(1,12):02d}/{year}",
        f"{day}th {month} {year}",
        f"{day} of {month} {year}",
    ]

    return random.choice(formats)


def create_utterance_with_entities(template_type: str) -> Dict:
    """Create a single utterance with entities"""
    first_name = random.choice(FIRST_NAMES)
    last_name = random.choice(LAST_NAMES)
    full_name = f"{first_name} {last_name}"
    city = random.choice(CITIES)
    location = random.choice(LOCATIONS)

    text = ""
    entities = []

    if template_type == "full_profile":
        # Complex utterance with multiple entities
        text = f"this is {full_name} from {city} my phone is "
        entities.append({
            "start": 8,
            "end": 8 + len(full_name),
            "label": "PERSON_NAME"
        })
        entities.append({
            "start": len(text) - len(city) - 1,
            "end": len(text) - 1,
            "label": "CITY"
        })

        phone, phone_len = generate_phone()
        phone_start = len(text)
        text += phone + " and email is "
        entities.append({
            "start": phone_start,
            "end": phone_start + len(phone),
            "label": "PHONE"
        })

        email = generate_email(first_name)
        email_start = len(text)
        text += email + " we can meet on "
        entities.append({
            "start": email_start,
            "end": email_start + len(email),
            "label": "EMAIL"
        })

        date = generate_date()
        date_start = len(text)
        text += date
        entities.append({
            "start": date_start,
            "end": date_start + len(date),
            "label": "DATE"
        })

    elif template_type == "credit_card":
        # Credit card utterance
        text = "uh actually my old card number maybe is "
        cc, cc_len = generate_credit_card()
        cc_start = len(text)
        text += cc + " i am not sure and my new phone is "
        entities.append({
            "start": cc_start,
            "end": cc_start + len(cc),
            "label": "CREDIT_CARD"
        })

        phone, phone_len = generate_phone()
        phone_start = len(text)
        text += phone + " also send email to "
        entities.append({
            "start": phone_start,
            "end": phone_start + len(phone),
            "label": "PHONE"
        })

        email = generate_email(first_name)
        email_start = len(text)
        text += email + " please"
        entities.append({
            "start": email_start,
            "end": email_start + len(email),
            "label": "EMAIL"
        })

    elif template_type == "travel":
        text = f"i am {full_name} travelling to {city} on "
        entities.append({
            "start": 5,
            "end": 5 + len(full_name),
            "label": "PERSON_NAME"
        })
        entities.append({
            "start": len(text) - len(city) - 4,
            "end": len(text) - 4,
            "label": "CITY"
        })

        date = generate_date()
        date_start = len(text)
        text += date
        entities.append({
            "start": date_start,
            "end": date_start + len(date),
            "label": "DATE"
        })

    elif template_type == "location":
        text = f"my name is {full_name} i work in {location} in {city}"
        entities.append({
            "start": 11,
            "end": 11 + len(full_name),
            "label": "PERSON_NAME"
        })
        loc_start = text.index(location)
        entities.append({
            "start": loc_start,
            "end": loc_start + len(location),
            "label": "LOCATION"
        })
        city_start = text.rindex(city)
        entities.append({
            "start": city_start,
            "end": city_start + len(city),
            "label": "CITY"
        })

    return {"text": text, "entities": sorted(entities, key=lambda x: x["start"])}


def generate_dataset(num_samples: int, output_file: str):
    """Generate a dataset with specified number of samples"""
    templates = ["full_profile", "credit_card", "travel", "location"]

    dataset = []
    for i in range(num_samples):
        template = random.choice(templates)
        utterance = create_utterance_with_entities(template)
        dataset.append({
            "id": f"gen_{i:04d}",
            **utterance
        })

    with open(output_file, 'w') as f:
        for item in dataset:
            f.write(json.dumps(item) + '\n')

    print(f"Generated {num_samples} samples in {output_file}")


if __name__ == "__main__":
    # Generate additional training data
    generate_dataset(700, "train.jsonl")

    # Generate additional dev data
    generate_dataset(150, "dev.jsonl")

    print("Data generation complete!")

